"""Configuration loading.

Two layers:
- syndicator.yaml      shared, committed, identical on both machines
- config.local.yaml    machine-specific paths, gitignored

The repo root is located by walking up from this file, so the CLI works from
any working directory.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, Field

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

ChannelKind = Literal["site", "social", "article"]

# Channels that exist in state tracking even when not (yet) generated by a pipeline.
ALL_CHANNELS = ["hugo", "facebook", "instagram", "x", "substack", "medium"]


class DeployCheck(BaseModel):
    timeout_seconds: int = 900
    poll_seconds: int = 30


class SiteConfig(BaseModel):
    base_url: str
    default_language: str = "en"
    deploy_check: DeployCheck = DeployCheck()


class TranslateConfig(BaseModel):
    model: str = "gpt-4.1"
    temperature: float = 0.3
    pirate_temperature: float = 0.9
    max_retries: int = 3


class SocialConfig(BaseModel):
    posts_per_week: int = 3


class CropFocusConfig(BaseModel):
    enabled: bool = True
    model: str = "gpt-5.4-mini"


class MediaConfig(BaseModel):
    crop_focus: CropFocusConfig = CropFocusConfig()


class ImageSpec(BaseModel):
    aspect: str | None = None  # e.g. "4:5"; None = keep aspect
    width: int | None = None
    height: int | None = None
    max_edge: int | None = None
    format: str = "jpeg"
    quality: int = 90


class VideoSpec(BaseModel):
    aspect: str | None = None  # e.g. "9:16"; None = keep aspect
    width: int | None = None
    height: int | None = None
    max_seconds: int | None = None
    pad_mode: Literal["blur", "black"] = "blur"


class ChannelConfig(BaseModel):
    kind: ChannelKind
    enabled: bool = True
    delivery: Literal["export", "api", "manual"] = "export"
    language: str = "en"
    link_mode: Literal["inline", "bio"] = "inline"
    max_media_per_post: int = 10
    max_chars: int | None = None
    caption_model: str = "gpt-5.5"
    image: ImageSpec = ImageSpec()
    video: VideoSpec = VideoSpec()


class LanguagesConfig(BaseModel):
    supported: list[str] = ["en", "de", "es", "fr", "it", "arrr"]


class SharedConfig(BaseModel):
    site: SiteConfig
    languages: LanguagesConfig = LanguagesConfig()
    translate: TranslateConfig = TranslateConfig()
    social: SocialConfig = SocialConfig()
    media: MediaConfig = MediaConfig()
    channels: dict[str, ChannelConfig]


class LocalConfig(BaseModel):
    saillog_dir: Path
    sailingnomads_dir: Path
    hugo_posts_subdir: str = "content/posts"
    converter_repo_dir: Path | None = None
    journeymap_bin: str = ""
    animatemap_bin: str = ""
    runs_dir: str = "runs"


class Config(BaseModel):
    shared: SharedConfig
    local: LocalConfig
    repo_root: Path = Field(default=REPO_ROOT)

    # --- derived paths -------------------------------------------------

    @property
    def data_dir(self) -> Path:
        """Synced data area inside the Logseq graph (mirrored by Syncthing)."""
        return self.local.saillog_dir / ".syndicator"

    @property
    def state_dir(self) -> Path:
        return self.data_dir / "state"

    @property
    def exports_dir(self) -> Path:
        return self.data_dir / "exports"

    @property
    def runs_dir(self) -> Path:
        p = Path(self.local.runs_dir)
        return p if p.is_absolute() else self.repo_root / p

    @property
    def journals_dir(self) -> Path:
        return self.local.saillog_dir / "journals"

    @property
    def pages_dir(self) -> Path:
        return self.local.saillog_dir / "pages"

    @property
    def hugo_posts_dir(self) -> Path:
        return self.local.sailingnomads_dir / self.local.hugo_posts_subdir

    def social_channels(self) -> dict[str, ChannelConfig]:
        return {
            name: ch
            for name, ch in self.shared.channels.items()
            if ch.kind == "social" and ch.enabled
        }


def load_config(repo_root: Path | None = None) -> Config:
    root = repo_root or REPO_ROOT
    shared_path = root / "syndicator.yaml"
    local_path = root / "config.local.yaml"

    if not shared_path.exists():
        raise FileNotFoundError(f"missing {shared_path}")
    if not local_path.exists():
        raise FileNotFoundError(
            f"missing {local_path} — copy config.local.yaml.example and adjust paths"
        )

    shared = SharedConfig.model_validate(yaml.safe_load(shared_path.read_text()))
    local = LocalConfig.model_validate(yaml.safe_load(local_path.read_text()))
    return Config(shared=shared, local=local, repo_root=root)
