#!/usr/bin/env bash
# Idempotently bcrypt-hash N8N_OWNER_PASSWORD into secrets/n8n_owner.env for Compose.
# Run before `docker compose up` (bootstrap also runs this).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ ! -f .env ]]; then
  echo "Missing .env — copy .env.example and fill N8N_OWNER_EMAIL / N8N_OWNER_PASSWORD." >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a
# shellcheck source=/dev/null
source .env
set +a

need() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "Missing required env: $name" >&2
    exit 1
  fi
}

need N8N_OWNER_EMAIL
need N8N_OWNER_PASSWORD

mkdir -p "$ROOT/secrets"
out="$ROOT/secrets/n8n_owner.env"

hash_password() {
  # Prefer host bcrypt; fall back to a one-shot container (Docker is required anyway).
  if python3 -c 'import bcrypt' >/dev/null 2>&1; then
    N8N_OWNER_PASSWORD="$N8N_OWNER_PASSWORD" python3 - <<'PY'
import bcrypt, os
password = os.environ["N8N_OWNER_PASSWORD"].encode()
print(bcrypt.hashpw(password, bcrypt.gensalt(rounds=10)).decode())
PY
    return
  fi
  printf '%s' "$N8N_OWNER_PASSWORD" | docker run --rm -i python:3.12-alpine sh -c '
    pip install -q bcrypt >/dev/null
    python -c "import bcrypt,sys; p=sys.stdin.buffer.read(); print(bcrypt.hashpw(p, bcrypt.gensalt(rounds=10)).decode())"
  '
}

echo "Hashing n8n owner password…"
raw_hash="$(hash_password)"
if [[ ! "$raw_hash" =~ ^\$2[aby]\$ ]]; then
  echo "Expected a bcrypt hash, got: ${raw_hash:0:20}…" >&2
  exit 1
fi

# Compose env_file interpolates $VAR; escape each $ as $$ for a literal hash.
escaped_hash="${raw_hash//\$/\$\$}"

umask 077
cat >"$out" <<EOF
# Generated by scripts/ensure-n8n-owner.sh — do not edit by hand.
N8N_INSTANCE_OWNER_PASSWORD_HASH=${escaped_hash}
EOF
chmod 600 "$out"
echo "Wrote $out"
