#!/usr/bin/env bash
# Idempotently bcrypt-hash N8N_OWNER_PASSWORD into the Compose owner env file.
# Run through `bin/syndicator init` before starting the stack.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/lib.sh
source "$ROOT/scripts/lib.sh"

force=0
if [[ "${1:-}" == "--force" ]]; then
  force=1
elif [[ "$#" -gt 0 ]]; then
  echo "Usage: $0 [--force]" >&2
  exit 2
fi

load_env
need_env N8N_OWNER_EMAIL
need_env N8N_OWNER_PASSWORD

out="$(resolve_from_root "${N8N_OWNER_ENV_FILE:-secrets/n8n_owner.env}")"
mkdir -p "$(dirname "$out")"
if [[ -s "$out" && "$force" -eq 0 ]]; then
  echo "n8n owner hash already present: $out"
  exit 0
fi

hash_password() {
  # Prefer host bcrypt; fall back to a one-shot container (Docker is required anyway).
  if python3 -c 'import bcrypt' >/dev/null 2>&1; then
    N8N_OWNER_PASSWORD="$N8N_OWNER_PASSWORD" python3 - <<'PY'
import bcrypt, os
password = os.environ["N8N_OWNER_PASSWORD"].encode()
print(bcrypt.hashpw(password, bcrypt.gensalt(rounds=10)).decode())
PY
    return
  fi
  printf '%s' "$N8N_OWNER_PASSWORD" | docker run --rm -i \
    "python:3.12-alpine@sha256:6d43704baacd1bfbe7c295d7f13079d5d8104ed33568873133f8fc69980419df" \
    sh -c '
    pip install --no-cache-dir -q bcrypt==5.0.0 >/dev/null
    python -c "import bcrypt,sys; p=sys.stdin.buffer.read(); print(bcrypt.hashpw(p, bcrypt.gensalt(rounds=10)).decode())"
  '
}

echo "Hashing n8n owner password…"
raw_hash="$(hash_password)"
if [[ ! "$raw_hash" =~ ^\$2[aby]\$ ]]; then
  echo "Expected a bcrypt hash, got: ${raw_hash:0:20}…" >&2
  exit 1
fi

# Compose env_file interpolates $VAR; escape each $ as $$ for a literal hash.
escaped_hash="${raw_hash//\$/\$\$}"

umask 077
cat >"$out" <<EOF
# Generated by scripts/ensure-n8n-owner.sh — do not edit by hand.
N8N_INSTANCE_OWNER_PASSWORD_HASH=${escaped_hash}
EOF
chmod 600 "$out"
echo "Wrote $out"
